---
title: "Plantas"
author: "Maxwel Coura Oliveira"
date: "8/16/2018"
output: html_document
---



```{r}
library(tidyverse)
library(ggplot2)
library(gganimate)
library(png)
library(grid)
library(ggthemes)
```

```{r Names Culturas, include=FALSE}
Culturas=read_csv("Culturas.csv")
```


```{r Names Culturas, include=FALSE}
Culturas$Culturas <-factor(Culturas$Culturas, levels=c("Citrus", "Cafe", "Milho", "Algodao", "Feijao", "Eucalipto", "Pastagem", "Arroz",  "Sorgo",  "Soja", "Cana-de-acuca", "HF", "Trigo", "Culturas de inverno (aveia, cevada, triticale)"), labels=c("Citrus", "Café", "Milho", "Algodão", "Feijão", "Eucalipto", "Pastagem", "Arroz",  "Sorgo",  "Soja", "Cana-de-açucar", "Olerícolas", "Trigo", "Culturas de inverno"))

Culturas$Regiao <-factor(Culturas$Regiao, levels=c("Brasil", "Norte", "Nordeste", "Centro", "Sudeste", "Sul"), labels=c("Brasil", "Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"))
```


```{r Culturas Figura}
Culturas <- Culturas %>% 
  mutate(Culturas = factor(Culturas, levels = c("Pastagem", "Eucalipto", "Citrus", "Café", "Olerícolas", "Algodão", "Sorgo", "Cana-de-açucar", "Arroz", "Culturas de inverno", "Trigo", "Feijão", "Milho", "Soja"))) %>% 
  filter(Culturas != "Pastagem")

ggplot(Culturas, aes(x=Culturas, y=Perc, fill=Culturas)) + geom_bar(stat="identity", width = 0.7, color="black", sort=TRUE) + facet_wrap(~Regiao) + coord_flip() + 
  theme_bw() +
 # geom_text(aes(label = str_c(round(Perc), "%")),
 #           position = position_stack(vjust = 1.1)) +
  scale_fill_manual(values=c("#41EAD4", "#80ff00", "#ffe6e6", "#D4C1EC", "#FB6376", "#DECBB7", "#21468B", "#ED7D3A", "#FFFFFF", "#74ACDFFF", "#fed100", "#000000", "#009b3a", "#D91023")) +
#  scale_color_material("teal") +
   theme(axis.text.y =element_text(size=10, color="black"), axis.text.x =element_text(size=10, color="black"), plot.title = element_text(size=18, hjust = 0.4, color="red"),  axis.title=element_text(size=15, face="bold"), plot.caption = element_text(size=6),
         strip.text.x = element_text(size=13, face="bold"), legend.position="none", panel.grid = element_blank()) + 
  labs(y="% respondents", x="", title = "", caption = "") +
  ggsave("Culturas.png", units="in", width=9, height=6, dpi=600)
```



```{r}
p <- ggplot(Culturas, aes(Culturas, y=Perc, fill=Culturas)) + geom_bar(stat="identity", width=0.5, color="black") + coord_flip() + 
    scale_fill_manual(values=c("#41EAD4", "#80ff00", "#ffe6e6", "#D4C1EC", "#FB6376", "#DECBB7", "#21468B", "#ED7D3A", "#FFFFFF", "#74ACDFFF", "#fed100", "#000000", "#009b3a", "#D91023")) +
  theme_bw() +
   theme(axis.text=element_text(size=12, color="black"), plot.subtitle = element_text(hjust = 0.5),  legend.position="none",
        axis.title=element_text(size=15, face="bold"), plot.title = element_text(size=15, face="bold", hjust = 0.5),
        panel.background = element_rect(fill="white", color = "black"),
        panel.grid.major = element_line(color = "white")) + #facet_wrap(~Region) + 
    labs(title='Região: {closest_state}', y="% respondentes", x="", subtitle = "Culturas mais manejadas no Brasil", caption = "Fonte: Weed Techonology Journal") + ylim(0,100) + #annotation_custom(g, xmin=-Inf, xmax=95, ymin=90, ymax=98) +
  transition_states(Regiao, transition_length = 3, state_length = 3) +
  enter_fade() +
  exit_shrink() +
  ease_aes('sine-in-out')  

anim <- animate(p)
magick::image_write(anim, path="culturas.gif")
```


```{r include=FALSE}
Data=read_csv("Plants.csv")

Data$Regiao <-factor(Data$Regiao, levels=c("Brasil", "Norte", "Nordeste", "Centro", "Sudeste", "Sul"), labels=c("Brasil", "Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"))

Data$Species <-factor(Data$Species, levels=c("trapoeraba", "capim-pe-de-galinha", "capim colchao", "buva", "azevem", "capim massambara", "leiteiro",  "corda-de-viola", "Palmer", "caruru", "picao", "capim-amargoso", "capim-branco", "poaia-branca",    "tiririca", "arroz vermelho"),labels=c("trapoeraba", "capim-pé-de-galinha", "capim colchão", "buva", "azevém", "capim massambará", "leiteiro",  "corda-de-viola", "Palmer amaranth", "caruru", "picão", "capim-amargoso", "capim-branco", "poaia-branca","tiririca", "arroz vermelho"))
```



```{r}
Data <- Data %>% 
  mutate(Species = factor(Species, levels = c("Palmer amaranth", "capim-branco", "capim massambará", "caruru", "azevém", "poaia-branca", "capim colchão", "arroz vermelho", "leiteiro", "picão", "tiririca", "capim-pé-de-galinha", "trapoeraba", "corda-de-viola",  "capim-amargoso", "buva")))

ggplot(Data) + aes(x=Species, y=Perc, fill=Species) + geom_bar(stat="identity", width = 0.7, color="black", sort=TRUE) + facet_wrap(~Regiao) + coord_flip() + #theme_economist_white() +
  theme_bw() +
    #annotate("text", x = 1, y = 95, label = c("n=256", "n=11", "n=22", "n=57", "n=93", "n=113"), size=3) +
  #geom_text() +
  scale_fill_manual(values=c("khaki1", "grey",  "red1", "purple","lightblue", "blue",  "turquoise1", "lightgreen", "palegoldenrod", "darkgreen", "pink",  "orange", "tomato4", "gold", "snow", "grey15")) +
   theme(axis.text.y =element_text(size=10, color="black"), axis.text.x =element_text(size=10, color="black"), plot.title = element_text(size=18, hjust = 0.0, color="red"),  axis.title = element_text(size=15, face="bold"), plot.caption = element_text(size=6), strip.text.x = element_text(size=13, face="bold"), legend.position="none", panel.grid = element_blank()) + 
  labs(y="% respondents", x="", title = "", caption = "") + ylim(0,100) 
```


```{r}
z <- ggplot(Data, aes(Species, y=Perc, fill=Species)) + geom_bar(stat="identity", width=0.5, color="black") + coord_flip() + 
    scale_fill_manual(values=c("khaki1", "grey",  "red1", "purple","lightblue", "blue",  "turquoise1", "lightgreen", "palegoldenrod", "darkgreen", "pink",  "orange", "tomato4", "gold", "snow", "grey15")) +
  theme_bw() +
   theme(axis.text=element_text(size=12, color="black"), plot.subtitle = element_text(hjust = 0.5),  legend.position="none",
        axis.title=element_text(size=15, face="bold"), plot.title = element_text(size=15, face="bold", hjust = 0.5),
        panel.background = element_rect(fill="white", color = "black"),
        panel.grid.major = element_line(color = "white")) + #facet_wrap(~Region) + 
  labs(title='Região: {closest_state}', y="% respondentes", x="", subtitle = "Plantas daninhas mais problemáticas no Brasil", caption = "Fonte: Weed Techonology Journal") + ylim(0,100) + #annotation_custom(g, xmin=-Inf, xmax=95, ymin=90, ymax=98) +
  transition_states(Regiao, transition_length = 3, state_length = 3) +
  enter_fade() +
  exit_shrink() +
  ease_aes('sine-in-out')  

anim <- animate(z)
magick::image_write(anim, path="daninhas.gif")
```